name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      
      - name: Build
        run: dotnet build "source" -c Release /p:Version=${VERSION}
      
      - name: Test
        run: dotnet test "tests" -c Release

      - name: Setup packing
        run: |
          cd source
      
      - name: Pack
        run: dotnet pack -c Release /p:Version=${VERSION} --no-build --output .

      - name: Add source
        run: dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --name github --username ${{ github.repository_owner }} --password ${{ github.token }} --store-password-in-clear-text
      
      - name: Push
        run: dotnet nuget push Unmanaged.${VERSION}.nupkg --source github --api-key ${NUGET_TOKEN}
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}