name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
      
      - name: Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
          
      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: Test
        run: dotnet test --logger trx --results-directory "TestResults/" --collect:"XPlat Code Coverage"

      - name: Analyze
        uses: bibipkins/dotnet-test-reporter@v1.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-title: 'Test Results'
          results-path: ./TestResults/*.trx
          coverage-path: ./TestResults/*/*.xml
          coverage-threshold: 80
        
      - name: Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dotnet-results-${{ matrix.dotnet-version }}
          path: TestResults-${{ matrix.dotnet-version }}
