name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
      
      - name: Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
          
      - name: Restore
        run: dotnet restore "Unmanaged/Unmanaged.csproj"

      - name: Build
        run: dotnet build "Unmanaged/Unmanaged.csproj"

      - name: Test
        run: dotnet test "Unmanaged Tests/Unmanaged Tests.csproj" --logger trx --results-directory "Unmanaged Tests/TestResults/" --collect:"XPlat Code Coverage"
        
      - name: Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dotnet-results-${{ matrix.dotnet-version }}
          path: TestResults-${{ matrix.dotnet-version }}
