name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '9.0.x' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          
      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: Test
        uses: zyborg/dotnet-tests-report@v1
        with:
          project_path: Tests
          report_name: Tests
          report_title: Tests
          github_token: ${{ secrets.GITHUB_TOKEN }}
        #run: dotnet test --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}"
        
      - name: Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dotnet-results-${{ matrix.dotnet-version }}
          path: TestResults-${{ matrix.dotnet-version }}
