name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - **

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      checks: write
      contents: write
      pull-requests: write
      actions: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Test project
        run: dotnet test "tests" -c Debug --logger "trx;LogFileName=test-results.trx"

      - name: Publish Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Report
          path: 'tests/TestResults/*.trx'
          reporter: dotnet-trx