name: Test

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.cs'
      - '**/*.csproj'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      checks: write
      contents: write
      pull-requests: write
      actions: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Test project
        run: dotnet test "tests" -c Debug --logger "trx" --collect:"XPlat Code Coverage"

      - name: Publish Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Report
          path: 'tests/TestResults/*.trx'
          reporter: dotnet-trx
          fail-on-error: false

      - name: Build coverage report
        uses: danielpalme/ReportGenerator-GitHub-Action@5.4.1
        with:
          reports: 'test/TestResults/*.xml'
          targetdir: 'coveragereport'
          reporttypes: 'HtmlInline;Cobertura;MarkdownSummaryGithub'
          tag: '${{ github.run_number }}_${{ github.run_id }}'
          toolpath: 'reportgeneratortool'

      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: CoverageReport
          path: coveragereport

      - name: Add comment to PR
        if: github.event_name == 'pull_request'
        run: gh pr comment $PR_NUMBER --body-file coveragereport/SummaryGithub.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
          
      - name: Publish coverage in build summary
        run: cat coveragereport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY
        shell: bash