name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install tools
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: List directory
        run: ls

      - name: Test project
        run: dotnet test -c Debug --collect:"XPlat Code Coverage" --results-directory:"TestResults"

      - name: Generate HTML report from test results
        if: always()
        uses: danielpalme/ReportGenerator-GitHub-Action@5.3.4
        with:
          license: ${{ secrets.REPORTGENERATOR_LICENSE }}
          reports: "TestResults/*/*.xml"
          targetdir: "coveragereport"
          reporttypes: "Html;Cobertura"
        
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Coverage
          path: coveragereport

      - name: Upload crash dumps
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Crash Dumps
          if-no-files-found: ignore
          path: "*/TestResults/*/*.dmp"
    
      - name: Upload test sequence
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Test Sequence
          path: "*/TestResults/*/Sequence_*.xml"
