name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Unmanaged Tests

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install tools
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: List directory
        run: ls

      - name: Test project
        run: dotnet test --collect:"XPlat Code Coverage" --results-directory:"TestResults" --blame-hang --blame-hang-dump-type full --blame-hang-timeout 5s

      - name: Generate HTML report from test results
        if: always()
        run: reportgenerator -reports:"TestResults/*/*.xml" -reporttypes:html -targetdir:"TestResults/html"
        
      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Test Results
          path: "TestResults/html"

      - name: Upload crash dumps
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Crash Dumps
          path: "TestResults/*.dmp"
